inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Metrics/MethodLength: 
  Max: 20

Metrics/ClassLength:
  Max: 1500

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  Exclude:
    - 'db'
    - 'node_modules'
